import {ArrowRight,CheckCircle2,Clock3} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {courses,lessons} from '../content';
import {mastery} from '../lib/progress';
import {useProgress} from '../lib/store';

export function CoursesPage(){return <section className="page container"><span className="eyebrow blue">Curriculum</span><h1>Choose your learning path.</h1><p className="lead">Follow the full course by chapter, or jump to the section you need. Every lesson includes explanations, worked examples, and at least ten exercises with hidden solutions.</p><div className="course-grid">{courses.map((c,i)=><Link className={`course-card ${c.color}`} to={`/courses/${c.id}`} key={c.id}><div className="course-number">0{i+1}</div><div className="course-icon">{c.icon}</div><h2>{c.title}</h2><p>{c.subtitle}</p><div className="course-meta"><span>{lessons.filter(l=>l.courseId===c.id).length} lessons</span><ArrowRight/></div></Link>)}</div></section>}
export function CoursePage(){
 const {courseId}=useParams();const course=courses.find(c=>c.id===courseId);const {progress}=useProgress();if(!course)return <section className="page container"><h1>Course not found</h1></section>;
 const items=lessons.filter(l=>l.courseId===course.id);const chapterMap=items.reduce<Record<string,typeof items>>((groups,lesson)=>{(groups[lesson.chapter]??=[]).push(lesson);return groups;},{});const chapters=Object.entries(chapterMap);
 return <section className="page"><div className={`course-hero ${course.color}`}><div className="container"><Link to="/courses">← All courses</Link><div className="course-hero-grid"><div><span className="eyebrow">Course track</span><h1>{course.title}</h1><p>{course.subtitle} Move in order or choose the idea you need today.</p></div><div className="course-progress"><strong>{items.length?Math.round(100*items.filter(l=>progress.completed.includes(l.id)).length/items.length):0}%</strong><span>course completion</span></div></div></div></div><div className="container curriculum">{chapters.map(([chapter,chapterLessons])=><section key={chapter}><div className="chapter-heading"><span>{chapter.match(/Chapter (\d+)/)?.[1].padStart(2,'0')}</span><div><h2>{chapter}</h2><p>{chapter==='Foundations'?'Begin here to build the language and intuition used later.':'Apply the foundations to deeper structures and models.'}</p></div></div><div className="chapter-lessons">{chapterLessons!.map((lesson)=>{const score=mastery(progress,lesson.id);const completed=progress.completed.includes(lesson.id);return <Link className="curriculum-row" to={`/lessons/${lesson.id}`} key={lesson.id}><div className="status-dot">{completed?<CheckCircle2/>:<span>{lesson.section}</span>}</div><div className="curriculum-copy"><div className="row wrap"><span className="eyebrow">{lesson.section}</span><span className="difficulty">{lesson.difficulty}</span></div><h3>{lesson.title}</h3><p>{lesson.description}</p></div><div className="lesson-stats"><span><Clock3 size={15}/>{lesson.estimatedMinutes} min</span><span>{score}% mastery</span></div><ArrowRight/></Link>})}</div></section>)}</div></section>;
}
