import {ArrowRight, BookOpenCheck, Brain, Compass, Sparkles} from 'lucide-react';
import {Link} from 'react-router-dom';
import {SearchBox} from '../components/Search';
import {courses,lessons} from '../content';
import {useProgress} from '../lib/store';

export function HomePage(){
 const {progress}=useProgress();const recent=progress.recent.map(id=>lessons.find(l=>l.id===id)).filter(Boolean).slice(-3).reverse();
 return <><section className="hero"><div className="hero-copy"><span className="pill"><Sparkles size={15}/> Mathematics, explained with care</span><h1>Build understanding.<br/><span>One clear step at a time.</span></h1><p>Learn Linear Algebra and Differential Equations from the beginning, see why each method works, and practice with support when you need it.</p><SearchBox large/><div className="popular"><span>Try:</span><Link to="/search?q=row%20reduction">row reduction</Link><Link to="/search?q=integrating%20factor">integrating factor</Link><Link to="/search?q=eigen">eigenvectors</Link></div></div><div className="hero-visual" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="math-card mc-one"><span>Direction</span><strong>Av = λv</strong></div><div className="math-card mc-two"><span>Change</span><strong>y′ = f(x,y)</strong></div><div className="math-card mc-three"><span>Progress</span><strong>{progress.completed.length} lessons complete</strong></div></div></section>
 <section className="section container"><div className="section-heading"><div><span className="eyebrow blue">Choose a path</span><h2>Two courses. One connected story.</h2></div><Link to="/courses">View all lessons <ArrowRight size={17}/></Link></div><div className="course-grid">{courses.map((course,i)=><Link className={`course-card ${course.color}`} to={`/courses/${course.id}`} key={course.id}><div className="course-number">0{i+1}</div><div className="course-icon">{course.icon}</div><h3>{course.title}</h3><p>{course.subtitle}</p><div className="course-meta"><span>{lessons.filter(l=>l.courseId===course.id).length} lessons</span><ArrowRight/></div></Link>)}</div></section>
 {recent.length>0&&<section className="section soft-section"><div className="container"><span className="eyebrow purple">Continue learning</span><h2>Pick up where you left off.</h2><div className="lesson-grid">{recent.map(lesson=><Link className="lesson-card" to={`/lessons/${lesson!.id}`} key={lesson!.id}><span>{lesson!.courseId==='linear-algebra'?'Linear Algebra':'Differential Equations'}</span><h3>{lesson!.title}</h3><p>{lesson!.description}</p></Link>)}</div></div></section>}
 <section className="section container"><div className="section-heading"><div><span className="eyebrow teal">Designed around understanding</span><h2>Study tools that respect your effort.</h2></div></div><div className="benefit-grid"><article><Compass/><h3>Start from the big idea</h3><p>Intuition comes before symbols, with every variable and operation explained.</p></article><article><Brain/><h3>Practice without spoilers</h3><p>Progressive hints guide the next move. Full solutions remain hidden until requested.</p></article><article><BookOpenCheck/><h3>Know what “mastery” means</h3><p>Progress comes from verified practice, not simply opening a lesson.</p></article></div></section>
 <section className="cta container"><div><span className="eyebrow">Your next step</span><h2>Begin with a foundation you can trust.</h2><p>No sign-up. Your guest progress saves automatically on this device.</p></div><Link className="button light" to="/courses">Explore the courses <ArrowRight size={17}/></Link></section></>;
}
