import type {Exercise,Step} from '../types/content';

const s=(text:string,math?:string):Step=>({text,...(math?{math}:{})});
const q=(lessonId:string,n:number,difficulty:1|2|3,prompt:string,math:string,answer:Exercise['answer'],hints:Step[],solutionSteps:Step[],answerType:Exercise['answerType']='numeric',choices?:string[]):Exercise=>({
 id:`${lessonId}-${n}`,lessonId,difficulty,prompt,math,answerType,
 ...(answer===undefined?{}:{answer}),...(choices?{choices}:{}),
 hints,solutionSteps,verificationStatus:'verified',
});

export const practiceAdditions:Record<string,Exercise[]>={
 systems:[
  q('systems',4,1,'Solve for y by subtracting the equations.',String.raw`x+3y=11,\qquad x+y=5`,3,
   [s('The x coefficients already agree.'),s('Subtract the second equation from the first.'),s('The difference gives an equation containing only y.')],
   [s('Subtract matching sides.',String.raw`(x+3y)-(x+y)=11-5`),s('Cancel x and combine y terms.',String.raw`2y=6`),s('Divide by 2.',String.raw`y=3`),s('Check by finding x from x+y=5.',String.raw`x=2,\quad2+9=11,\quad2+3=5`)]),
  q('systems',5,1,'Find x in the triangular system.',String.raw`\begin{cases}2x+y=7\\3y=9\end{cases}`,2,
   [s('Start with the equation that has one unknown.'),s('Solve 3y=9.'),s('Substitute that y into the first equation.')],
   [s('Divide the second equation by 3.',String.raw`y=3`),s('Substitute y=3.',String.raw`2x+3=7`),s('Subtract 3, then divide by 2.',String.raw`2x=4\Rightarrow x=2`),s('Both original equations now hold.',String.raw`2(2)+3=7,\quad3(3)=9`)]),
  q('systems',6,2,'Solve this system. Enter x and y as a column matrix.',String.raw`\begin{cases}2x+3y=1\\4x-y=9\end{cases}`,[[2],[-1]],
   [s('Make the x coefficients equal.'),s('Double the first equation, then subtract the second.'),s('Find y before substituting for x.')],
   [s('Double equation 1.',String.raw`4x+6y=2`),s('Subtract equation 2.',String.raw`7y=-7\Rightarrow y=-1`),s('Substitute into equation 1.',String.raw`2x-3=1\Rightarrow x=2`),s('Check equation 2.',String.raw`4(2)-(-1)=9`)],'matrix'),
  q('systems',7,2,'How many free variables appear in this reduced system?',String.raw`\left[\begin{array}{ccc|c}1&0&2&3\\0&1&-1&4\end{array}\right]`,1,
   [s('Count the variable columns, excluding the augmented column.'),s('Identify the columns containing pivots.'),s('A variable column without a pivot is free.')],
   [s('There are three variables x, y, z and pivots in columns 1 and 2.'),s('Column 3 has no pivot, so z=t is free.',String.raw`z=t`),s('Solve the pivot equations.',String.raw`x=3-2t,\qquad y=4+t`),s('The one parameter describes all solutions.',String.raw`(x,y,z)=(3-2t,4+t,t)`)]),
  q('systems',8,2,'Is this matrix in RREF?',String.raw`\begin{bmatrix}1&2&0\\0&1&3\end{bmatrix}`,'No',
   [s('Check every pivot column, not only each pivot value.'),s('In RREF a pivot must be the only nonzero entry in its column.'),s('Inspect the entry above the pivot in column 2.')],
   [s('The pivots are 1, but column 2 has a 2 above its pivot.'),s('Clear that entry with a reversible row replacement.',String.raw`R_1\leftarrow R_1-2R_2`),s('The resulting matrix is RREF.',String.raw`\begin{bmatrix}1&0&-6\\0&1&3\end{bmatrix}`)],'multiple-choice',['Yes','No']),
  q('systems',9,3,'Which value of a makes the system inconsistent?',String.raw`x+y=1,\qquad2x+ay=3`,2,
   [s('Subtract twice equation 1 from equation 2.'),s('For inconsistency the remaining y coefficient must be zero.'),s('Check that the remaining constant is nonzero.')],
   [s('Eliminate x.',String.raw`(a-2)y=1`),s('If a=2, this becomes a contradiction.',String.raw`0=1`),s('For every other a, solve uniquely.',String.raw`y=\frac1{a-2},\quad x=1-\frac1{a-2}`)]),
  q('systems',10,3,'Solve the three-variable system. Enter a column matrix.',String.raw`\begin{cases}x+y+z=6\\x-y+z=2\\2x+y-z=1\end{cases}`,[[1],[2],[3]],
   [s('Subtract equation 2 from equation 1.'),s('Use the resulting y value in equations 1 and 3.'),s('Eliminate z from those two remaining equations.')],
   [s('Subtract equations 1 and 2.',String.raw`2y=4\Rightarrow y=2`),s('Insert y=2 into equations 1 and 3.',String.raw`x+z=4,\quad2x-z=-1`),s('Add to find x; then solve for z.',String.raw`3x=3\Rightarrow x=1,\quad z=3`),s('Check all three original equations.',String.raw`1+2+3=6,\quad1-2+3=2,\quad2+2-3=1`)],'matrix'),
 ],
 vectors:[
  q('vectors',4,1,'Find the scalar k satisfying this equation.',String.raw`k\begin{bmatrix}2\\-1\end{bmatrix}=\begin{bmatrix}6\\-3\end{bmatrix}`,3,
   [s('Use either component to solve for k.'),s('The first component says 2k=6.'),s('Use the second component to check your result.')],
   [s('Compare the first components.',String.raw`2k=6\Rightarrow k=3`),s('Verify the second components.',String.raw`3(-1)=-3`)]),
  q('vectors',5,1,'Subtract w from v. Enter a column matrix.',String.raw`v=\begin{bmatrix}5\\-2\\1\end{bmatrix},\quad w=\begin{bmatrix}2\\3\\-4\end{bmatrix}`,[[3],[-5],[5]],
   [s('Subtract matching components.'),s('Subtracting a negative number means adding its opposite.'),s('Keep all three component positions.')],
   [s('Subtract in each coordinate.',String.raw`v-w=\begin{bmatrix}5-2\\-2-3\\1-(-4)\end{bmatrix}`),s('Simplify.',String.raw`v-w=\begin{bmatrix}3\\-5\\5\end{bmatrix}`)],'matrix'),
  q('vectors',6,2,'Find coefficients a,b. Enter them as a column matrix.',String.raw`a\begin{bmatrix}1\\1\end{bmatrix}+b\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}4\\2\end{bmatrix}`,[[3],[1]],
   [s('Turn vector equality into two scalar equations.'),s('Adding the equations eliminates b.'),s('Substitute the resulting a to get b.')],
   [s('Match components.',String.raw`a+b=4,\quad a-b=2`),s('Add both equations.',String.raw`2a=6\Rightarrow a=3`),s('Substitute a=3.',String.raw`3+b=4\Rightarrow b=1`),s('Verify the combination.',String.raw`3\begin{bmatrix}1\\1\end{bmatrix}+\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}4\\2\end{bmatrix}`)],'matrix'),
  q('vectors',7,2,'What is the dimension of this span?',String.raw`\operatorname{span}\left\{\begin{bmatrix}1\\0\\0\end{bmatrix},\begin{bmatrix}0\\1\\0\end{bmatrix}\right\}`,2,
   [s('Check whether either direction is redundant.'),s('All combinations have third coordinate zero.'),s('Count the independent supplied directions.')],
   [s('A combination has the form (a,b,0).'),s('The only way it equals zero is a=b=0, so the two vectors are independent.'),s('They span the xy-plane, a space of dimension 2.')]),
  q('vectors',8,2,'Are these three vectors independent?',String.raw`v_1=\begin{bmatrix}1\\0\end{bmatrix},\quad v_2=\begin{bmatrix}0\\1\end{bmatrix},\quad v_3=\begin{bmatrix}1\\1\end{bmatrix}`,'No',
   [s('Try writing the third vector using the first two.'),s('Look at v₁+v₂.'),s('Rearrange the relation to give a nontrivial zero combination.')],
   [s('The third vector equals the sum of the first two.',String.raw`v_3=v_1+v_2`),s('Move all terms to one side.',String.raw`v_1+v_2-v_3=0`),s('The coefficients 1,1,−1 are not all zero, so the vectors are dependent.')],'multiple-choice',['Yes','No']),
  q('vectors',9,3,'For what value of a are these two vectors dependent?',String.raw`v=\begin{bmatrix}1\\2\end{bmatrix},\quad w=\begin{bmatrix}3\\a\end{bmatrix}`,6,
   [s('Dependence here means w is a scalar multiple of nonzero v.'),s('The first coordinate fixes the multiplier as 3.'),s('Alternatively set the two-by-two determinant to zero.')],
   [s('Use the first coordinate to fix the multiplier.',String.raw`w=3v\Rightarrow a=3(2)=6`),s('Check using the determinant.',String.raw`\det\begin{bmatrix}1&3\\2&a\end{bmatrix}=a-6=0`),s('At a=6, both vectors lie on the same line.')]),
  q('vectors',10,3,'Is this target in the given span?',String.raw`b=\begin{bmatrix}1\\1\\1\end{bmatrix},\quad W=\operatorname{span}\left\{\begin{bmatrix}1\\0\\1\end{bmatrix},\begin{bmatrix}0\\1\\1\end{bmatrix}\right\}`,'No',
   [s('Write a general combination of the two generators.'),s('Match the first two coordinates to the target.'),s('Check whether their sum matches the third coordinate.')],
   [s('Every combination has this form.',String.raw`a\begin{bmatrix}1\\0\\1\end{bmatrix}+b\begin{bmatrix}0\\1\\1\end{bmatrix}=\begin{bmatrix}a\\b\\a+b\end{bmatrix}`),s('The first two coordinates force a=1,b=1.'),s('The third becomes 2, while the target needs 1. There is no solution.')],'multiple-choice',['Yes','No']),
 ],
 projection:[
  q('projection',4,1,'Find the squared length of v.',String.raw`v=\begin{bmatrix}3\\4\end{bmatrix}`,25,
   [s('Squared length is v·v.'),s('Square each component and add.'),s('Do not take a square root: the question asks for squared length.')],
   [s('Apply the dot product.',String.raw`\|v\|^2=3^2+4^2`),s('Add the squares.',String.raw`9+16=25`),s('The length itself is 5, while the squared length is 25.')]),
  q('projection',5,1,'Choose k to make the vectors orthogonal.',String.raw`\begin{bmatrix}1\\2\end{bmatrix}\cdot\begin{bmatrix}k\\3\end{bmatrix}=0`,-6,
   [s('Orthogonal means the dot product is zero.'),s('Expand the dot product.'),s('Solve the resulting linear equation.')],
   [s('Compute the dot product.',String.raw`k+2(3)=0`),s('Subtract 6.',String.raw`k=-6`),s('Check: −6+6=0.')]),
  q('projection',6,2,'Project v onto u. Enter a column matrix.',String.raw`v=\begin{bmatrix}5\\2\end{bmatrix},\quad u=\begin{bmatrix}2\\0\end{bmatrix}`,[[5],[0]],
   [s('u is not a unit vector, so include its squared length.'),s('Compute v·u and u·u.'),s('Multiply the ratio by u.')],
   [s('Compute the two dot products.',String.raw`v\cdot u=10,\quad u\cdot u=4`),s('Compute the coefficient.',String.raw`c=\frac{10}{4}=\frac52`),s('Multiply by u.',String.raw`p=\frac52\begin{bmatrix}2\\0\end{bmatrix}=\begin{bmatrix}5\\0\end{bmatrix}`)],'matrix'),
  q('projection',7,2,'Find the residual after projection onto u. Enter a column matrix.',String.raw`v=\begin{bmatrix}4\\0\end{bmatrix},\quad u=\begin{bmatrix}1\\1\end{bmatrix}`,[[2],[-2]],
   [s('First compute the projection.'),s('Its coefficient is (v·u)/(u·u).'),s('The residual is v minus that projection.')],
   [s('Compute the coefficient.',String.raw`c=\frac4{2}=2`),s('Find the projection.',String.raw`p=\begin{bmatrix}2\\2\end{bmatrix}`),s('Subtract p from v.',String.raw`r=\begin{bmatrix}4\\0\end{bmatrix}-\begin{bmatrix}2\\2\end{bmatrix}=\begin{bmatrix}2\\-2\end{bmatrix}`),s('Check orthogonality.',String.raw`r\cdot u=2-2=0`)],'matrix'),
  q('projection',8,2,'Normalize this vector by dividing by its length. Enter a column matrix.',String.raw`v=\begin{bmatrix}3\\4\end{bmatrix}`,[[.6],[.8]],
   [s('Compute the length, not its square.'),s('Use the square root of 3²+4².'),s('Divide every component by the same length.')],
   [s('Find the length.',String.raw`\|v\|=\sqrt{9+16}=5`),s('Divide by 5.',String.raw`e=\begin{bmatrix}3/5\\4/5\end{bmatrix}`),s('Check the unit length.',String.raw`(3/5)^2+(4/5)^2=1`)],'matrix'),
  q('projection',9,3,'Perform the second Gram–Schmidt subtraction. Enter the unnormalized u₂.',String.raw`v_1=\begin{bmatrix}1\\1\end{bmatrix},\quad v_2=\begin{bmatrix}3\\1\end{bmatrix}`,[[1],[-1]],
   [s('Set u₁=v₁.'),s('Remove the projection of v₂ onto u₁.'),s('Normalize only if requested; this question asks for the unnormalized result.')],
   [s('Find the projection coefficient.',String.raw`\frac{v_2\cdot u_1}{u_1\cdot u_1}=\frac{4}{2}=2`),s('Subtract twice u₁.',String.raw`u_2=\begin{bmatrix}3\\1\end{bmatrix}-2\begin{bmatrix}1\\1\end{bmatrix}=\begin{bmatrix}1\\-1\end{bmatrix}`),s('Confirm that u₁·u₂=1−1=0.')],'matrix'),
  q('projection',10,3,'Find the squared distance from v to the line spanned by u.',String.raw`v=\begin{bmatrix}3\\1\end{bmatrix},\quad u=\begin{bmatrix}1\\2\end{bmatrix}`,5,
   [s('The projection is the nearest point on the line.'),s('Use the residual v−projᵤv.'),s('Squared distance is the dot product of the residual with itself.')],
   [s('Find the coefficient.',String.raw`c=\frac{3+2}{1+4}=1`),s('Subtract the projected point.',String.raw`r=\begin{bmatrix}3\\1\end{bmatrix}-\begin{bmatrix}1\\2\end{bmatrix}=\begin{bmatrix}2\\-1\end{bmatrix}`),s('Calculate the squared residual length.',String.raw`d^2=2^2+(-1)^2=5`),s('The residual is perpendicular: 2(1)−1(2)=0.')]),
 ],
 eigenvalues:[
  q('eigenvalues',4,1,'Find the eigenvalue of the vertical unit vector.',String.raw`A=\begin{bmatrix}2&0\\0&-3\end{bmatrix},\quad v=\begin{bmatrix}0\\1\end{bmatrix}`,-3,
   [s('Multiply A by v.'),s('Compare Av with a scalar multiple of v.'),s('A negative eigenvalue reverses the direction along the same line.')],
   [s('Multiply.',String.raw`Av=\begin{bmatrix}0\\-3\end{bmatrix}`),s('Recognize the scalar multiple.',String.raw`Av=-3v\Rightarrow\lambda=-3`)]),
  q('eigenvalues',5,1,'Compute Av. Enter a column matrix.',String.raw`A=\begin{bmatrix}1&2\\3&4\end{bmatrix},\quad v=\begin{bmatrix}2\\-1\end{bmatrix}`,[[0],[2]],
   [s('Use row-by-column products.'),s('The first output is 1(2)+2(−1).'),s('The second output is 3(2)+4(−1).')],
   [s('Write both row products.',String.raw`Av=\begin{bmatrix}2-2\\6-4\end{bmatrix}`),s('Simplify.',String.raw`Av=\begin{bmatrix}0\\2\end{bmatrix}`)],'matrix'),
  q('eigenvalues',6,2,'Find the larger eigenvalue.',String.raw`A=\begin{bmatrix}3&1\\1&3\end{bmatrix}`,4,
   [s('Form det(A−λI).'),s('Expand (3−λ)²−1.'),s('Factor the resulting quadratic.')],
   [s('Form the characteristic equation.',String.raw`(3-\lambda)^2-1=0`),s('Expand and factor.',String.raw`\lambda^2-6\lambda+8=(\lambda-2)(\lambda-4)`),s('The roots are 2 and 4, so the larger is 4.')]),
  q('eigenvalues',7,2,'Is the given vector an eigenvector?',String.raw`A=\begin{bmatrix}2&1\\0&3\end{bmatrix},\quad v=\begin{bmatrix}1\\0\end{bmatrix}`,'Yes',
   [s('Check multiplication directly.'),s('The output must equal λ times the entire input vector.'),s('Compare both components of Av with v.')],
   [s('Multiply.',String.raw`Av=\begin{bmatrix}2\\0\end{bmatrix}`),s('This equals 2v; v is nonzero, so it is an eigenvector with λ=2.')],'multiple-choice',['Yes','No']),
  q('eigenvalues',8,2,'Find the dimension of the eigenspace for λ=2.',String.raw`A=\begin{bmatrix}2&1\\0&2\end{bmatrix}`,1,
   [s('Solve (A−2I)v=0.'),s('One equation forces the second component to zero.'),s('Count the remaining independent direction.')],
   [s('Subtract 2I.',String.raw`A-2I=\begin{bmatrix}0&1\\0&0\end{bmatrix}`),s('The eigenvector equation is y=0, with x arbitrary.'),s('The eigenspace is span{(1,0)}, so its dimension is 1. The algebraic multiplicity is 2.')]),
  q('eigenvalues',9,3,'For which value of k is zero an eigenvalue?',String.raw`A=\begin{bmatrix}1&2\\3&k\end{bmatrix}`,6,
   [s('Zero is an eigenvalue precisely when A is singular.'),s('Set det(A)=0.'),s('Expand the two-by-two determinant.')],
   [s('Compute the determinant.',String.raw`\det A=k-6`),s('Set it to zero.',String.raw`k-6=0\Rightarrow k=6`),s('At k=6, v=(−2,1) is nonzero and Av=0, confirming λ=0.')]),
  q('eigenvalues',10,3,'How many distinct real eigenvalues does this matrix have?',String.raw`A=\begin{bmatrix}0&-2\\2&0\end{bmatrix}`,0,
   [s('Form the characteristic determinant.'),s('Check whether its roots are real.'),s('A square plus a positive constant cannot vanish for real λ.')],
   [s('Compute the determinant.',String.raw`\det(A-\lambda I)=\lambda^2+4`),s('The roots are ±2i, so there are no real eigenvalues.'),s('Geometrically the matrix rotates every real nonzero vector by 90 degrees and scales by 2.')]),
 ],
 separable:[
  q('separable',4,1,'Find C for this initial condition.',String.raw`y=\frac{x^3}{3}+C,\quad y(0)=2`,2,
   [s('Substitute x=0 into the family.'),s('The x³ term vanishes.'),s('Match the given value of y.')],
   [s('Evaluate the family at zero.',String.raw`2=0+C`),s('Thus C=2 and y=x³/3+2; its derivative is x².')]),
  q('separable',5,1,'For y′=−2y, what is y′ when y=3?',String.raw`y'=-2y`, -6,
   [s('This asks for the rate, not for the entire solution.'),s('Substitute y=3 into the right-hand side.'),s('The negative sign indicates decay at this positive y.')],
   [s('Substitute the given value.',String.raw`y'=-2(3)`),s('Multiply.',String.raw`y'=-6`)]),
  q('separable',6,2,'Find y(2) for the initial-value problem.',String.raw`y'=2x,\quad y(0)=1`,5,
   [s('Integrate the rate.'),s('Use the initial condition to determine the constant.'),s('Evaluate the resulting function at x=2.')],
   [s('Integrate.',String.raw`y=x^2+C`),s('Apply y(0)=1.',String.raw`C=1`),s('Evaluate.',String.raw`y(2)=4+1=5`),s('Differentiate to check y′=2x.')]),
  q('separable',7,2,'Solve the initial-value problem. Compare your expression with the solution.',String.raw`y'=xy,\quad y(0)=2`,undefined,
   [s('Separate y from x where y is nonzero.'),s('Integrate 1/y and x.'),s('Exponentiate, then apply y(0)=2.')],
   [s('Separate and integrate.',String.raw`\int\frac{dy}{y}=\int x\,dx\Rightarrow\ln|y|=\frac{x^2}{2}+C_1`),s('Absorb the sign and exponential constant.',String.raw`y=Ce^{x^2/2}`),s('Use the initial condition.',String.raw`2=C\Rightarrow y=2e^{x^2/2}`),s('Differentiate to verify.',String.raw`y'=2xe^{x^2/2}=xy`)],'self-check'),
  q('separable',8,2,'Find the squared value [y(1)]² on the positive branch.',String.raw`y'=\frac{x}{y},\quad y(0)=2`,5,
   [s('Multiply by y before integrating.'),s('Integrate ydy and xdx.'),s('Use the positive square root selected by y(0)=2.')],
   [s('Separate and integrate.',String.raw`y\,dy=x\,dx\Rightarrow\frac{y^2}{2}=\frac{x^2}{2}+C`),s('Apply the initial condition.',String.raw`y^2=x^2+4`),s('Choose the positive branch and evaluate.',String.raw`y=\sqrt{x^2+4},\quad y(1)=\sqrt5,\quad [y(1)]^2=5`)]),
  q('separable',9,3,'Find the positive blow-up time of this solution.',String.raw`y'=y^2,\quad y(0)=2`,.5,
   [s('Separate using y⁻²dy=dx.'),s('Integrate and use the initial value.'),s('The solution blows up where its denominator vanishes.')],
   [s('Integrate.',String.raw`-\frac1y=x+C`),s('Apply y(0)=2.',String.raw`C=-\frac12`),s('Isolate y.',String.raw`y=\frac{2}{1-2x}`),s('The denominator first vanishes at x=1/2; the interval containing zero is (−∞,1/2).')]),
  q('separable',10,3,'Solve this logistic initial-value problem. Compare your full solution.',String.raw`y'=y(1-y),\quad y(0)=\frac12`,undefined,
   [s('Check equilibrium solutions before dividing.'),s('Use 1/[y(1−y)]=1/y+1/(1−y).'),s('Integrate the partial fractions and apply the initial value.')],
   [s('Equilibria y=0 and y=1 do not satisfy this initial condition. Separate on 0<y<1.',String.raw`\frac{dy}{y(1-y)}=dx`),s('Integrate the partial fractions.',String.raw`\ln|y|-\ln|1-y|=x+C`),s('Use y(0)=1/2 to obtain C=0, then exponentiate.',String.raw`\frac{y}{1-y}=e^x`),s('Solve for y.',String.raw`y=\frac1{1+e^{-x}}`),s('Differentiate: y′=e⁻ˣ/(1+e⁻ˣ)²=y(1−y), and y(0)=1/2.')],'self-check'),
 ],
 'linear-ode':[
  q('linear-ode',4,1,'Find P after putting the equation in standard form.',String.raw`2y'+6y=8`,3,
   [s('Make the coefficient of y′ equal to 1.'),s('Divide every term by 2.'),s('P is the coefficient of y in the normalized equation.')],
   [s('Divide by 2.',String.raw`y'+3y=4`),s('Read P=3 and Q=4 from standard form.')]),
  q('linear-ode',5,1,'Find the constant equilibrium solution.',String.raw`y'+4y=12`,3,
   [s('A constant solution has derivative zero.'),s('Set y′=0.'),s('Solve the remaining algebraic equation.')],
   [s('Set the derivative to zero.',String.raw`4y=12`),s('Divide by 4.',String.raw`y=3`),s('The constant function has y′=0, so 0+4(3)=12.')]),
  q('linear-ode',6,2,'Find C in the initial-value solution.',String.raw`y=2+Ce^{-3x},\quad y(0)=-1`,-3,
   [s('Use e⁰=1.'),s('Substitute the initial condition.'),s('Subtract the equilibrium value 2.')],
   [s('Evaluate at zero.',String.raw`-1=2+C`),s('Subtract 2.',String.raw`C=-3`),s('The selected function is y=2−3e⁻³ˣ.')]),
  q('linear-ode',7,2,'Find y(2) for the initial-value problem on x>0.',String.raw`y'+\frac2x y=3x,\quad y(1)=2`,3.3125,
   [s('Compute μ=e^(∫2/x dx) on x>0.'),s('Rewrite the equation as (x²y)′=3x³.'),s('Apply the stated initial condition to check the resulting formula.')],
   [s('The integrating factor is x².',String.raw`\mu=e^{2\ln x}=x^2`),s('Multiply and integrate.',String.raw`(x^2y)'=3x^3\Rightarrow x^2y=\frac34x^4+C`),s('Apply the condition.',String.raw`2=\frac34+C\Rightarrow C=\frac54`),s('Divide and evaluate at x=2.',String.raw`y=\frac34x^2+\frac{5}{4x^2},\quad y(2)=3+\frac5{16}=\frac{53}{16}`)]),
  q('linear-ode',8,2,'Solve the equation on x>0. Compare your general solution.',String.raw`y'-\frac1x y=x^2`,undefined,
   [s('P=−1/x.'),s('Use integrating factor 1/x on x>0.'),s('Integrate the derivative of y/x, then multiply by x.')],
   [s('Find the integrating factor.',String.raw`\mu=e^{-\ln x}=\frac1x`),s('Multiply and use the product rule.',String.raw`\left(\frac yx\right)'=x`),s('Integrate.',String.raw`\frac yx=\frac{x^2}{2}+C`),s('Isolate and check.',String.raw`y=\frac{x^3}{2}+Cx,\quad y'-\frac yx=x^2`)],'self-check'),
  q('linear-ode',9,3,'Find y(0) for this family of solutions.',String.raw`y'+y=e^x,\qquad y=\frac12e^x+3e^{-x}`,3.5,
   [s('Check that differentiating the family satisfies the equation.'),s('At zero both exponentials equal 1.'),s('Add the two contributions.')],
   [s('Differentiate and substitute.',String.raw`y'=\frac12e^x-3e^{-x},\quad y'+y=e^x`),s('Evaluate at zero.',String.raw`y(0)=\frac12+3=\frac72`)]),
  q('linear-ode',10,3,'Solve the initial-value problem. Compare your full expression.',String.raw`y'+2y=x,\quad y(0)=0`,undefined,
   [s('Use μ=e²ˣ.'),s('Integrate xe²ˣ by parts.'),s('Divide by μ and determine C from y(0)=0.')],
   [s('Multiply by the integrating factor.',String.raw`(e^{2x}y)'=xe^{2x}`),s('Integrate by parts with u=x and dv=e²ˣdx.',String.raw`e^{2x}y=\frac{x}{2}e^{2x}-\frac14e^{2x}+C`),s('Divide and apply y(0)=0.',String.raw`y=\frac x2-\frac14+Ce^{-2x},\quad C=\frac14`),s('State the solution.',String.raw`y=\frac x2-\frac14+\frac14e^{-2x}`),s('Differentiate and substitute: y′+2y=x, and the initial value is zero.')],'self-check'),
 ],
 'second-order':[
  q('second-order',4,1,'Find the repeated characteristic root.',String.raw`y''-6y'+9y=0`,3,
   [s('Replace derivatives with powers of r.'),s('Factor the quadratic.'),s('A squared linear factor gives one repeated root.')],
   [s('Form the characteristic equation.',String.raw`r^2-6r+9=0`),s('Factor.',String.raw`(r-3)^2=0\Rightarrow r=3`),s('The general solution is (C₁+C₂x)e³ˣ.')]),
  q('second-order',5,1,'Find the angular frequency of the oscillation.',String.raw`y''+9y=0`,3,
   [s('Compare with y″+ω²y=0.'),s('Frequency is the square root of the coefficient 9.'),s('Use the positive value of ω.')],
   [s('Find the characteristic roots.',String.raw`r^2+9=0\Rightarrow r=\pm3i`),s('The real family is C₁cos(3x)+C₂sin(3x), with angular frequency 3.')]),
  q('second-order',6,2,'Solve the initial-value problem. Compare your solution.',String.raw`y''-3y'+2y=0,\quad y(0)=0,\quad y'(0)=1`,undefined,
   [s('Factor the characteristic quadratic.'),s('Use y=C₁eˣ+C₂e²ˣ.'),s('Differentiate, then solve the two equations for the constants.')],
   [s('Factor and write the general solution.',String.raw`(r-1)(r-2)=0,\quad y=C_1e^x+C_2e^{2x}`),s('Apply both initial conditions.',String.raw`C_1+C_2=0,\quad C_1+2C_2=1`),s('Subtract to find the constants.',String.raw`C_2=1,\quad C_1=-1`),s('State and check.',String.raw`y=e^{2x}-e^x,\quad y(0)=0,\quad y'(0)=1`)],'self-check'),
  q('second-order',7,2,'Find C₂ in the repeated-root solution.',String.raw`y=(C_1+C_2x)e^{-x},\quad y(0)=2,\quad y'(0)=0`,2,
   [s('The first condition determines C₁.'),s('Differentiate using the product rule.'),s('At zero, y′(0)=C₂−C₁.')],
   [s('Apply y(0)=2.',String.raw`C_1=2`),s('Differentiate.',String.raw`y'=(C_2-C_1-C_2x)e^{-x}`),s('Apply y′(0)=0.',String.raw`C_2-2=0\Rightarrow C_2=2`)]),
  q('second-order',8,2,'How many arbitrary constants are needed in the general solution?',String.raw`y'''-y'=0`,3,
   [s('The equation is homogeneous and third order.'),s('The characteristic equation factors as r(r²−1)=0.'),s('Each distinct root supplies an independent solution.')],
   [s('Factor the characteristic polynomial.',String.raw`r(r-1)(r+1)=0`),s('Use one independent solution per root.',String.raw`y=C_1+C_2e^x+C_3e^{-x}`),s('There are three independent constants, matching the order.')]),
  q('second-order',9,3,'Find one particular solution using resonance. Compare your expression.',String.raw`y''+y=\cos x`,undefined,
   [s('cos x and sin x already belong to the homogeneous solution.'),s('Multiply the usual trigonometric trial by x.'),s('Differentiate a trial Ax sin x and substitute.')],
   [s('The complementary family is C₁cos x+C₂sin x; the forcing resonates.'),s('Try a convenient resonant trial and differentiate.',String.raw`y_p=Ax\sin x,\quad y_p'=A\sin x+Ax\cos x`),s('Differentiate again.',String.raw`y_p''=2A\cos x-Ax\sin x`),s('Substitute and match coefficients.',String.raw`y_p''+y_p=2A\cos x=\cos x\Rightarrow A=\frac12`),s('One particular solution is yₚ=(x/2)sin x.')],'self-check'),
  q('second-order',10,3,'Solve the boundary-value problem. Compare your expression.',String.raw`y''=0,\quad y(0)=1,\quad y(2)=5`,undefined,
   [s('Integrate y″=0 twice.'),s('Use the condition at zero for the intercept.'),s('Use the other endpoint to determine the slope.')],
   [s('Integrate once and twice.',String.raw`y'=C_1,\quad y=C_1x+C_2`),s('Apply y(0)=1.',String.raw`C_2=1`),s('Apply y(2)=5.',String.raw`2C_1+1=5\Rightarrow C_1=2`),s('The solution y=2x+1 has y″=0 and both requested endpoint values.')],'self-check'),
 ],
 euler:[
  q('euler',4,1,'Compute the first Euler estimate.',String.raw`y'=x+y,\quad x_0=0,\quad y_0=1,\quad h=0.2`,1.2,
   [s('Evaluate f at the starting pair (0,1).'),s('Multiply the slope by h.'),s('Add the increment to y₀.')],
   [s('Compute the starting slope.',String.raw`f(0,1)=1`),s('Update.',String.raw`y_1=1+0.2(1)=1.2`),s('This is an approximation at x₁=0.2.')]),
  q('euler',5,1,'Find x₃ after three steps.',String.raw`x_0=1,\quad h=0.25`,1.75,
   [s('Each step adds h to x.'),s('After n steps xₙ=x₀+nh.'),s('Use n=3.')],
   [s('Use the grid formula.',String.raw`x_3=1+3(0.25)`),s('Simplify.',String.raw`x_3=1.75`)]),
  q('euler',6,2,'Compute two Euler steps and enter y₂.',String.raw`y'=x+y,\quad(x_0,y_0)=(0,1),\quad h=0.5`,2.5,
   [s('Compute y₁ and x₁ first.'),s('Evaluate the next slope at (x₁,y₁), not at the starting point.'),s('Add h times that next slope.')],
   [s('First slope and update.',String.raw`f(0,1)=1,\quad y_1=1+0.5=1.5`),s('Update x and find the next slope.',String.raw`x_1=0.5,\quad f(0.5,1.5)=2`),s('Take the second step.',String.raw`y_2=1.5+0.5(2)=2.5`)]),
  q('euler',7,2,'Compute the first improved Euler (Heun) estimate.',String.raw`y'=y,\quad(x_0,y_0)=(0,1),\quad h=0.2`,1.22,
   [s('Predict an endpoint using an ordinary Euler step.'),s('Evaluate the slope at the predicted endpoint.'),s('Correct using the average of the start and predicted endpoint slopes.')],
   [s('The starting slope is k₁=1. Predict the endpoint.',String.raw`\widetilde y_1=1+0.2(1)=1.2`),s('The predicted endpoint slope is k₂=1.2.'),s('Use the average slope.',String.raw`y_1=1+\frac{0.2}{2}(1+1.2)=1.22`),s('The exact value e⁰·² is approximately 1.22140; this corrected estimate is still approximate.')]),
  q('euler',8,2,'Find the Euler estimate y₂ for constant-rate growth.',String.raw`y'=3,\quad y_0=2,\quad h=0.25`,3.5,
   [s('The slope is always 3, at every grid point.'),s('Each step increases y by 0.25·3.'),s('Take two equal increments.')],
   [s('First step.',String.raw`y_1=2+0.25(3)=2.75`),s('Second step.',String.raw`y_2=2.75+0.25(3)=3.5`),s('Here Euler is exact at the grid points because the solution y=2+3x is a straight line.')]),
  q('euler',9,3,'For strict decay stability of Euler on y′=−4y, what upper bound must h stay below?',String.raw`y'=-4y,\quad h>0`,.5,
   [s('Euler multiplies y by 1−4h each step.'),s('Strict stability requires |1−4h|<1.'),s('Solve the double inequality for positive h.')],
   [s('Write the stability inequality.',String.raw`-1<1-4h<1`),s('Solve its two sides.',String.raw`0<h<\frac12`),s('h must stay below 1/2. At the bound the multiplier is −1, so the estimate oscillates without decaying.')]),
  q('euler',10,3,'Does Euler underestimate or overestimate y(0.2) here?',String.raw`y'=y,\quad y(0)=1,\quad h=0.1`,'Underestimate',
   [s('Compute the two Euler steps.'),s('Compare with the exact exponential.'),s('For positive y the exponential is convex, so tangent steps fall below the true curve.')],
   [s('Euler gives the values.',String.raw`y_1=1.1,\quad y_2=1.21`),s('The exact value is e⁰·²≈1.221402758.'),s('1.21 is smaller, so this estimate underestimates the true value by about 0.011402758.')],'multiple-choice',['Underestimate','Overestimate','Exactly equal']),
 ],
};
