import {useState} from 'react';
import {useNavigate,Link} from 'react-router-dom';
import {Search as SearchIcon,ArrowUpRight} from 'lucide-react';
import {searchLessons} from '../lib/search';
export function SearchBox({large=false}:{large?:boolean}){
 const [query,setQuery]=useState('');const [focused,setFocused]=useState(false);const navigate=useNavigate();const suggestions=query.trim()?searchLessons(query).slice(0,4):[];
 return <div className={`search-wrap ${large?'large':''}`} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false);}}><form className="search-box" role="search" onSubmit={e=>{e.preventDefault();setFocused(false);navigate(`/search?q=${encodeURIComponent(query)}`);}}><SearchIcon size={large?23:18}/><label className="sr-only" htmlFor={large?'hero-search':'nav-search'}>Search topics, formulas, or equations</label><input id={large?'hero-search':'nav-search'} value={query} onFocus={()=>setFocused(true)} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setFocused(false);}} placeholder="Try ‘eigenvectors’ or ‘integrating factor’" autoComplete="off"/><button aria-label="Search lessons" type="submit"><ArrowUpRight size={20}/></button></form>{focused&&query.trim()&&<div className="suggestions" aria-label="Search suggestions">{suggestions.length?suggestions.map(({lesson})=><Link key={lesson.id} to={`/lessons/${lesson.id}`} onClick={()=>setFocused(false)}><span>{lesson.title}</span><small>{lesson.courseId==='linear-algebra'?'Linear Algebra':'Differential Equations'}</small></Link>):<p>No indexed lessons match. Try a broader topic.</p>}<Link to={`/search?q=${encodeURIComponent(query)}`} onClick={()=>setFocused(false)}>See all results →</Link></div>}</div>;
}
export function Highlight({text,query}:{text:string,query:string}){const token=query.trim();const index=text.toLowerCase().indexOf(token.toLowerCase());if(!token||index<0)return <>{text}</>;return <>{text.slice(0,index)}<mark>{text.slice(index,index+token.length)}</mark>{text.slice(index+token.length)}</>;}
