"""Detailed replacements for the original starter examples, with exact checks."""
import sympy as S

def expand_starters(lessons,audit,st):
    x=S.Symbol('x',real=True);C,C1,C2=S.symbols('C C_1 C_2',real=True);M=S.Matrix
    by_id={l['id']:l for l in lessons}
    def put(id,index,steps,answer,proofs):
        assertions=[]
        for lhs,rhs in proofs:
            delta=S.simplify(lhs-rhs)
            assert delta==(S.zeros(*delta.shape) if isinstance(delta,S.MatrixBase) else 0),(id,index,lhs,rhs)
            assertions.append({'left':str(lhs),'right':str(rhs)})
        audit.append({'id':f'{id}-detailed-example-{index+1}','assertions':assertions})
        example=by_id[id]['examples'][index];example['steps']=[st(*s) if isinstance(s,tuple) else st(s) for s in steps];example['finalAnswer']=st('Final result',answer)
    put('systems',0,[
      ('Write the system in a consistent variable order.',r'x+y=5,\quad x-y=1'),
      ('Add the entire left sides and the entire right sides.',r'(x+y)+(x-y)=5+1'),
      ('Group like terms; y and −y cancel.',r'(x+x)+(y-y)=6'),
      ('Combine the remaining x terms.',r'2x=6'),
      ('Divide both sides by the nonzero coefficient 2.',r'x=\frac62=3'),
      ('Insert x=3 into the first original equation.',r'3+y=5'),
      ('Subtract 3 from both sides.',r'y=5-3=2'),
      ('Check the first original equation.',r'3+2=5'),
      ('Check the second original equation.',r'3-2=1')],r'x=3,\quad y=2',[(S.Integer(3)+2,5),(S.Integer(3)-2,1)])
    put('systems',1,[
      ('Encode the coefficients and constants; the last column is augmented.',r'\left[\begin{array}{cc|c}1&2&7\\2&-1&4\end{array}\right]'),
      ('Multiply every entry of row 1 by 2.',r'2R_1=(2,4,14)'),
      ('Subtract those entries from row 2 in the same column order.',r'2-2=0,\quad -1-4=-5,\quad 4-14=-10'),
      ('Record the updated matrix.',r'\left[\begin{array}{cc|c}1&2&7\\0&-5&-10\end{array}\right]'),
      ('Divide every entry of row 2 by −5.',r'\frac0{-5}=0,\quad\frac{-5}{-5}=1,\quad\frac{-10}{-5}=2'),
      ('Clear the coefficient above the second pivot by subtracting twice the new row 2.',r'1-2(0)=1,\quad2-2(1)=0,\quad7-2(2)=3'),
      ('Read the two pivot equations.',r'\left[\begin{array}{cc|c}1&0&3\\0&1&2\end{array}\right]'),
      ('Verify the values in both original equations.',r'3+2(2)=7,\quad2(3)-2=4')],r'x=3,\quad y=2',[(M([[1,2],[2,-1]])*M([3,2]),M([7,4]))])
    put('systems',2,[
      ('Write the two equations.',r'x+2y=4,\quad2x+4y=8'),
      ('Subtract twice the first equation from the second.',r'(2x+4y)-2(x+2y)=8-2(4)'),
      ('Distribute, then combine like terms.',r'2x+4y-2x-4y=0'),
      ('The second restriction is redundant; it becomes 0=0.',r'\left[\begin{array}{cc|c}1&2&4\\0&0&0\end{array}\right]'),
      ('The y column has no pivot, so choose an arbitrary real parameter.',r'y=t,\quad t\in\mathbb R'),
      ('Insert y=t into the remaining equation and subtract 2t.',r'x+2t=4\Rightarrow x=4-2t'),
      ('Verify the first equation for every t.',r'(4-2t)+2t=4'),
      ('Verify the second equation for every t.',r'2(4-2t)+4t=8')],r'x=4-2t,\quad y=t,\quad t\in\mathbb R',[(M([[1,2],[2,4]])*M([4-2*x,x]),M([4,8]))])
    put('vectors',0,[('Write the vectors.',r'v=\begin{bmatrix}1\\2\end{bmatrix},\quad w=\begin{bmatrix}3\\-1\end{bmatrix}'),('Both vectors have two coordinates, so addition is defined.'),('Add the first coordinates.',r'1+3=4'),('Add the second coordinates; adding −1 means subtracting 1.',r'2+(-1)=1'),('Keep the results in the original coordinate order.',r'v+w=\begin{bmatrix}4\\1\end{bmatrix}')],r'v+w=\begin{bmatrix}4\\1\end{bmatrix}',[(M([1,2])+M([3,-1]),M([4,1]))])
    put('vectors',1,[('Use the two standard basis vectors.',r'e_1=\begin{bmatrix}1\\0\end{bmatrix},\quad e_2=\begin{bmatrix}0\\1\end{bmatrix}'),('Multiply each coordinate of e₁ by 3.',r'3e_1=\begin{bmatrix}3(1)\\3(0)\end{bmatrix}=\begin{bmatrix}3\\0\end{bmatrix}'),('Multiply each coordinate of e₂ by −2.',r'-2e_2=\begin{bmatrix}-2(0)\\-2(1)\end{bmatrix}=\begin{bmatrix}0\\-2\end{bmatrix}'),('Add the two scaled vectors coordinate by coordinate.',r'\begin{bmatrix}3+0\\0-2\end{bmatrix}=\begin{bmatrix}3\\-2\end{bmatrix}'),('The same construction works for arbitrary a and b, proving the span is R².',r'ae_1+be_2=\begin{bmatrix}a\\b\end{bmatrix}')],r'3e_1-2e_2=\begin{bmatrix}3\\-2\end{bmatrix}',[(3*M([1,0])-2*M([0,1]),M([3,-2]))])
    put('vectors',2,[('Compare the vectors.',r'v=\begin{bmatrix}2\\1\end{bmatrix},\quad w=\begin{bmatrix}6\\3\end{bmatrix}'),('Use the first coordinates to find a possible scale factor.',r'\frac62=3'),('Confirm that the second coordinate has the same scale factor.',r'3(1)=3'),('Multiply the entire first vector to confirm the relation.',r'3v=\begin{bmatrix}3(2)\\3(1)\end{bmatrix}=w'),('Move w to the left to exhibit a zero combination.',r'3v-w=\begin{bmatrix}0\\0\end{bmatrix}'),('The coefficients 3 and −1 are not both zero. Thus the vectors are dependent and span only the line in direction v.')],r'3v-w=0\quad\text{(linearly dependent)}',[(3*M([2,1])-M([6,3]),M([0,0]))])
    for index,(v,u) in enumerate([(M([3,4]),M([1,0])),(M([3,1]),M([1,1])),(M([2,0]),M([1,1]))]):
        num=v.dot(u);den=u.dot(u);coef=num/den;p=coef*u;res=v-p
        steps=[('Write the vector and the direction of projection.',rf'v={S.latex(v)},\quad u={S.latex(u)}'),('Multiply corresponding coordinates to compute the numerator.',rf'v\cdot u=({v[0]})({u[0]})+({v[1]})({u[1]})={num}'),('Compute the direction vector dotted with itself.',rf'u\cdot u=({u[0]})^2+({u[1]})^2={den}'),('Divide the numerator by the nonzero denominator.',rf'c=\frac{{{num}}}{{{den}}}={S.latex(coef)}')]
        for j in range(2):steps.append((f'Multiply coordinate {j+1} of u by this coefficient.',rf'p_{{{j+1}}}=({S.latex(coef)})({u[j]})={S.latex(p[j])}'))
        steps += [('Assemble the projection.',rf'p={S.latex(p)}'),('Subtract the projection to isolate the perpendicular residual.',rf'r=v-p={S.latex(res)}'),('Check that the residual is perpendicular to u.',rf'r\cdot u=({res[0]})({u[0]})+({res[1]})({u[1]})=0')]
        answer=rf'p={S.latex(p)}'
        if index==2:
            steps += [('For Gram–Schmidt, this residual is the second orthogonal direction.'),('Each direction has length √2. Divide every coordinate by that length.',r'q_1=\frac1{\sqrt2}\begin{bmatrix}1\\1\end{bmatrix},\quad q_2=\frac1{\sqrt2}\begin{bmatrix}1\\-1\end{bmatrix}')];answer=r'q_1=\frac1{\sqrt2}\begin{bmatrix}1\\1\end{bmatrix},\quad q_2=\frac1{\sqrt2}\begin{bmatrix}1\\-1\end{bmatrix}'
        put('projection',index,steps,answer,[(res.dot(u),0),(p+res,v)])
    put('eigenvalues',0,[('Write the diagonal matrix.',r'A=\begin{bmatrix}2&0\\0&3\end{bmatrix}'),('Test the nonzero horizontal unit vector.',r'v_1=\begin{bmatrix}1\\0\end{bmatrix}'),('Use the first row for its first output coordinate.',r'2(1)+0(0)=2'),('Use the second row for its second output coordinate.',r'0(1)+3(0)=0'),('Compare the output with a scalar multiple of the input.',r'Av_1=\begin{bmatrix}2\\0\end{bmatrix}=2v_1'),('Repeat with the nonzero vertical unit vector.',r'v_2=\begin{bmatrix}0\\1\end{bmatrix}'),('Calculate its two output coordinates.',r'2(0)+0(1)=0,\quad0(0)+3(1)=3'),('The second direction is scaled by 3.',r'Av_2=3v_2')],r'\lambda_1=2,\quad v_1=\begin{bmatrix}1\\0\end{bmatrix},\quad\lambda_2=3,\quad v_2=\begin{bmatrix}0\\1\end{bmatrix}',[(M([[2,0],[0,3]])*M([1,0]),2*M([1,0])),(M([[2,0],[0,3]])*M([0,1]),3*M([0,1]))])
    put('eigenvalues',1,[('Start with the triangular matrix.',r'A=\begin{bmatrix}2&1\\0&3\end{bmatrix}'),('Subtract λ from the diagonal entries only.',r'A-\lambda I=\begin{bmatrix}2-\lambda&1\\0&3-\lambda\end{bmatrix}'),('Apply the 2×2 determinant rule.',r'\det(A-\lambda I)=(2-\lambda)(3-\lambda)-1(0)'),('An eigenvalue makes this determinant zero.',r'(2-\lambda)(3-\lambda)=0'),('Use the zero-product property on each factor.',r'\lambda=2,\quad\lambda=3'),('For λ=2, the first row requires y=0; choose a nonzero x.',r'v_1=\begin{bmatrix}1\\0\end{bmatrix}'),('For λ=3, the first row of (A−3I)v=0 is −x+y=0.',r'-x+y=0\Rightarrow y=x'),('Choose x=1; then y=1, giving a nonzero eigenvector.',r'v_2=\begin{bmatrix}1\\1\end{bmatrix}'),('Check its first output coordinate.',r'2(1)+1(1)=3'),('Check its second output coordinate and compare with 3v₂.',r'0(1)+3(1)=3,\quad Av_2=3v_2')],r'\lambda=2:\ v_1=\begin{bmatrix}1\\0\end{bmatrix},\quad\lambda=3:\ v_2=\begin{bmatrix}1\\1\end{bmatrix}',[(M([[2,1],[0,3]])*M([1,1]),3*M([1,1])),(M([[2,1],[0,3]])*M([1,0]),2*M([1,0]))])
    put('eigenvalues',2,[('Write the rotation matrix.',r'A=\begin{bmatrix}0&-1\\1&0\end{bmatrix}'),('Subtract λ from both diagonal entries.',r'A-\lambda I=\begin{bmatrix}-\lambda&-1\\1&-\lambda\end{bmatrix}'),('Multiply the main-diagonal entries.',r'(-\lambda)(-\lambda)=\lambda^2'),('Multiply the opposite-diagonal entries.',r'(-1)(1)=-1'),('Subtract the second product.',r'\det(A-\lambda I)=\lambda^2-(-1)=\lambda^2+1'),('Set the determinant to zero and subtract 1.',r'\lambda^2=-1'),('No real number squares to −1, so there are no real eigenvalues or nonzero real eigenvectors.'),('Over the complex numbers, i²=−1 supplies two roots.',r'\lambda=i,\quad\lambda=-i'),('For λ=i, solve −ix−y=0 and choose x=1.',r'v_+=\begin{bmatrix}1\\-i\end{bmatrix}'),('Conjugation gives the eigenvector for λ=−i.',r'v_-=\begin{bmatrix}1\\i\end{bmatrix}')],r'\text{No real eigenvectors};\quad\lambda=\pm i',[(M([[0,-1],[1,0]])*M([1,-S.I]),S.I*M([1,-S.I]))])
    put('separable',0,[('Write the known rate and initial value.',r'y\prime=2x,\quad y(0)=3'),('Integrate both sides with respect to x.',r'y=\int2x\,dx'),('Take out the constant 2.',r'y=2\int x\,dx'),('Use the power rule for integration and add one arbitrary constant.',r'y=2\frac{x^2}{2}+C=x^2+C'),('Insert x=0 and y=3.',r'3=0^2+C'),('Solve for the integration constant.',r'C=3'),('Differentiate to check the rate.',r'\frac{d}{dx}(x^2+3)=2x'),('Check the initial value separately.',r'y(0)=0+3=3')],r'y=x^2+3',[(S.diff(x*x+3,x),2*x),((x*x+3).subs(x,0),3)])
    put('separable',1,[('Write the equation and initial condition.',r'y\prime=2y,\quad y(0)=3'),('The constant function y=0 solves the equation, but cannot satisfy the given initial value.'),('For the nonzero solution divide by y and multiply by dx.',r'\frac{dy}{y}=2\,dx'),('Integrate each side with its own variable.',r'\int\frac{dy}{y}=\int2\,dx'),('Use the logarithm and constant-rate antiderivatives.',r'\ln|y|=2x+C_1'),('Exponentiate both sides.',r'|y|=e^{2x+C_1}=e^{C_1}e^{2x}'),('Absorb magnitude and sign into one nonzero constant.',r'y=Ce^{2x}'),('Insert x=0; the exponential becomes 1.',r'3=Ce^0=C'),('Substitute the determined constant.',r'y=3e^{2x}'),('Differentiate and compare with 2y.',r'y\prime=3(2)e^{2x}=2y')],r'y=3e^{2x}',[(S.diff(3*S.exp(2*x),x),6*S.exp(2*x))])
    put('separable',2,[('Write the equation and initial value.',r'y\prime=y^2,\quad y(0)=1'),('The equilibrium y=0 does not satisfy this initial condition. For a nonzero solution, divide by y².',r'y^{-2}\,dy=dx'),('Integrate both sides.',r'\int y^{-2}\,dy=\int1\,dx'),('Apply the power rule with exponent −2; increasing it by 1 gives −1.',r'\frac{y^{-1}}{-1}=x+C'),('Insert x=0 and y=1.',r'-1=0+C\Rightarrow C=-1'),('Substitute the constant into the implicit equation.',r'-\frac1y=x-1'),('Multiply by −1 and take reciprocals.',r'\frac1y=1-x\Rightarrow y=\frac1{1-x}'),('The denominator is zero at x=1. The maximal interval containing the initial point is x<1.'),('Differentiate with the chain rule; two negative signs cancel.',r'y\prime=(1-x)^{-2}=y^2')],r'y=\frac1{1-x},\quad x<1',[(S.diff(1/(1-x),x),1/(1-x)**2)])
    put('linear-ode',0,[('Put the equation in standard linear form and identify P and Q.',r'y\prime+2y=6,\quad P=2,\quad Q=6'),('Integrate P to obtain the integrating-factor exponent.',r'\int P\,dx=2x'),('Exponentiate; an arbitrary multiplier can be omitted for the integrating factor.',r'\mu=e^{2x}'),('Multiply every term by μ.',r'e^{2x}y\prime+2e^{2x}y=6e^{2x}'),('The product rule identifies the entire left side.',r'(e^{2x}y)\prime=e^{2x}y\prime+2e^{2x}y'),('Integrate the resulting product derivative.',r'e^{2x}y=\int6e^{2x}\,dx'),('Use the exponential antiderivative; divide by its inner rate 2.',r'e^{2x}y=\frac62e^{2x}+C=3e^{2x}+C'),('Divide every term by e²ˣ, which is never zero.',r'y=3+Ce^{-2x}'),('Differentiate and substitute to verify cancellation.',r'y\prime=-2Ce^{-2x},\quad y\prime+2y=6')],r'y=3+Ce^{-2x}',[(S.diff(3+C*S.exp(-2*x),x)+2*(3+C*S.exp(-2*x)),6)])
    put('linear-ode',1,[('Use the general family from the preceding example and the given condition.',r'y=3+Ce^{-2x},\quad y(0)=5'),('Insert x=0 into the family.',r'5=3+Ce^0'),('Use e⁰=1.',r'5=3+C'),('Subtract 3 from both sides.',r'C=2'),('Insert this constant to obtain the selected solution.',r'y=3+2e^{-2x}'),('Differentiate the exponential; multiply by its inner derivative −2.',r'y\prime=2(-2)e^{-2x}=-4e^{-2x}'),('Substitute y and y′ into the original equation.',r'-4e^{-2x}+2(3+2e^{-2x})=6'),('Verify the initial value.',r'y(0)=3+2=5')],r'y=3+2e^{-2x}',[(S.diff(3+2*S.exp(-2*x),x)+2*(3+2*S.exp(-2*x)),6)])
    f=x*x/3+C/x
    put('linear-ode',2,[('Work on x>0, where the coefficient 1/x is continuous.',r'y\prime+\frac1xy=x'),('Identify the coefficient of y and integrate it.',r'P(x)=\frac1x,\quad\int P(x)\,dx=\ln x'),('Exponentiate to obtain the integrating factor.',r'\mu=e^{\ln x}=x'),('Multiply every term of the original equation by x.',r'xy\prime+y=x^2'),('Use the product rule to combine the left side.',r'(xy)\prime=x^2'),('Integrate both sides.',r'xy=\int x^2\,dx=\frac{x^3}3+C'),('Divide both terms by x.',r'y=\frac{x^2}3+\frac Cx'),('Differentiate each term.',r'y\prime=\frac{2x}3-\frac C{x^2}'),('Divide the proposed solution by x.',r'\frac yx=\frac x3+\frac C{x^2}'),('Add; the constant-dependent terms cancel.',r'y\prime+\frac yx=\frac{2x}3+\frac x3=x')],r'y=\frac{x^2}3+\frac Cx,\quad x>0',[(S.diff(f,x)+f/x,x)])
    put('second-order',0,[('Write the homogeneous equation.',r'y\prime\prime-3y\prime+2y=0'),('Try an exponential and compute its derivatives.',r'y=e^{rx},\quad y\prime=re^{rx},\quad y\prime\prime=r^2e^{rx}'),('Insert all three expressions into the equation.',r'r^2e^{rx}-3re^{rx}+2e^{rx}=0'),('Factor out and divide by eʳˣ, which is never zero.',r'r^2-3r+2=0'),('Find two numbers whose sum is −3 and product is 2: −1 and −2.',r'(r-1)(r-2)=0'),('Set each factor equal to zero.',r'r=1,\quad r=2'),('Each distinct root gives an independent exponential.',r'y_1=e^x,\quad y_2=e^{2x}'),('Combine the independent solutions with arbitrary constants.',r'y=C_1e^x+C_2e^{2x}')],r'y=C_1e^x+C_2e^{2x}',[(S.diff(S.exp(x),x,2)-3*S.diff(S.exp(x),x)+2*S.exp(x),0),(S.diff(S.exp(2*x),x,2)-3*S.diff(S.exp(2*x),x)+2*S.exp(2*x),0)])
    put('second-order',1,[('Write the ODE and its characteristic equation.',r'y\prime\prime+2y\prime+y=0,\quad r^2+2r+1=0'),('Recognize a perfect square and solve for the repeated root.',r'(r+1)^2=0\Rightarrow r=-1'),('The root gives e⁻ˣ; multiplicity two requires the second function x e⁻ˣ.',r'y_1=e^{-x},\quad y_2=xe^{-x}'),('Differentiate the second function using the product rule.',r'y_2\prime=1(e^{-x})+x(-e^{-x})=(1-x)e^{-x}'),('Differentiate this product once more.',r'y_2\prime\prime=(-1)e^{-x}+(1-x)(-e^{-x})=(x-2)e^{-x}'),('Substitute into the ODE and factor out e⁻ˣ.',r'y_2\prime\prime+2y_2\prime+y_2=[(x-2)+2(1-x)+x]e^{-x}'),('Expand the bracket and cancel every term.',r'x-2+2-2x+x=0'),('The two functions are independent; their Wronskian is nonzero.',r'W=e^{-x}(1-x)e^{-x}-xe^{-x}(-e^{-x})=e^{-2x}'),('State their full linear combination.',r'y=(C_1+C_2x)e^{-x}')],r'y=(C_1+C_2x)e^{-x}',[(S.diff(x*S.exp(-x),x,2)+2*S.diff(x*S.exp(-x),x)+x*S.exp(-x),0)])
    put('second-order',2,[('Write the ODE and both initial conditions.',r'y\prime\prime+4y=0,\quad y(0)=1,\quad y\prime(0)=0'),('The exponential trial yields this characteristic equation.',r'r^2+4=0'),('Subtract 4 and take complex square roots.',r'r^2=-4\Rightarrow r=\pm2i'),('The imaginary pair yields real sine and cosine solutions.',r'y=C_1\cos(2x)+C_2\sin(2x)'),('Insert x=0 into the position condition; use cos 0=1 and sin 0=0.',r'1=C_1(1)+C_2(0)\Rightarrow C_1=1'),('Differentiate the full family using the chain rule.',r'y\prime=-2C_1\sin(2x)+2C_2\cos(2x)'),('Insert x=0 into the velocity condition.',r'0=-2C_1(0)+2C_2(1)=2C_2'),('Divide by 2 to obtain the remaining constant.',r'C_2=0'),('Insert both constants and verify the ODE.',r'y=\cos(2x),\quad y\prime\prime=-4\cos(2x)')],r'y=\cos(2x)',[(S.diff(S.cos(2*x),x,2)+4*S.cos(2*x),0)])
    put('euler',0,[('Write the equation, initial point, and step size.',r'y\prime=y,\quad x_0=0,\quad y_0=1,\quad h=0.1'),('Advance the independent variable by one step.',r'x_1=x_0+h=0.1'),('Evaluate the slope at the current point, not the new point.',r'f(x_0,y_0)=y_0=1'),('Multiply the slope by the step size to obtain the predicted change.',r'\Delta y=hf(x_0,y_0)=0.1(1)=0.1'),('Add this change to the current value.',r'y_1=y_0+\Delta y=1+0.1=1.1'),('The exact solution is eˣ; compare at the same x₁.',r'y(0.1)=e^{0.1}\approx1.10517'),('The signed approximation error is numerical minus exact.',r'1.1-1.10517\approx-0.00517')],r'y(0.1)\approx1.1',[(S.Rational(1)+S.Rational(1,10),S.Rational(11,10))])
    put('euler',1,[('Continue the equation y′=y using the previous computed point.',r'x_1=0.1,\quad y_1=1.1,\quad h=0.1'),('Advance x by the same step size.',r'x_2=x_1+h=0.2'),('Evaluate the next slope using the approximate y₁.',r'f(x_1,y_1)=1.1'),('Multiply by the step size.',r'\Delta y=0.1(1.1)=0.11'),('Add the predicted change to y₁.',r'y_2=1.1+0.11=1.21'),('Compare with the exact value at the same x₂.',r'e^{0.2}\approx1.22140'),('Compute numerical minus exact for the signed error.',r'1.21-1.22140\approx-0.01140')],r'y(0.2)\approx1.21',[(S.Rational(11,10)+S.Rational(1,10)*S.Rational(11,10),S.Rational(121,100))])
    put('euler',2,[('Write the rapidly decaying ODE and its initial value.',r'y\prime=-10y,\quad y(0)=1'),('Its exact solution decays toward zero.',r'y=e^{-10x}'),('Apply the Euler recurrence with h=0.3.',r'y_{n+1}=y_n+0.3(-10y_n)'),('Multiply the step size by the coefficient.',r'0.3(-10)=-3'),('Combine the current value and the predicted change.',r'y_{n+1}=(1-3)y_n=-2y_n'),('Compute each step from the previous approximation.',r'y_0=1,\quad y_1=-2(1)=-2,\quad y_2=-2(-2)=4,\quad y_3=-2(4)=-8'),('For decay, the magnitude of the multiplier must be less than 1.',r'|1-10h|<1'),('Write the equivalent double inequality.',r'-1<1-10h<1'),('Subtract 1 from each part.',r'-2<-10h<0'),('Divide by −10 and reverse the inequality directions.',r'0<h<0.2'),('The chosen h=0.3 is outside that range, explaining the alternating, growing approximation.')],r'0<h<0.2\quad\text{for stable decay}',[(S.Rational(1)+S.Rational(3,10)*(-10),-2)])
